jwt:
  expiration: 60000
  secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onboarding
    username: root
    password: root
  driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect

  flyway:
    locations: classpath:db/migration,classpath:db/testdata